FROM node:12

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY src/package*.json ./

# RUN npm install
# If you are building your code for production
RUN npm install --only=production

RUN npm audit fix

# Bundle app source
COPY ./src .

COPY environments/.env.prod .env
COPY .env.example .env.example

EXPOSE 3001
CMD [ "npm", "start" ]
